# Generated by Django 2.2.2 on 2020-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Faculty', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.CharField(max_length=20)),
                ('Fee', models.IntegerField()),
                ('Duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Contact', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
