# Generated by Django 2.2.2 on 2020-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Date',
            field=models.CharField(max_length=20),
        ),
    ]
