# Generated by Django 2.2.2 on 2020-10-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201029_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=20)),
                ('e_course', models.CharField(max_length=20)),
                ('e_faculty', models.CharField(max_length=20)),
            ],
        ),
    ]
